language: minimal

sudo: false

matrix:
  fast_finish: true
  include:
    - name: "legacy_python"
      env: PY=2.7
    - name: "default"
      env: PY=3.7
    - name: "coding_standards"
      env: PY=3.7

before_install:
  - wget http://bit.ly/miniconda -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
  - conda update conda --quiet
  - conda config --add channels conda-forge --force
  - conda create --name TEST python=$PY --file requirements.txt --file requirements-dev.txt
  - source activate TEST

# Test source distribution.
install:
  - python setup.py sdist && version=$(python setup.py --version) && pushd dist  && pip install --no-deps --force-reinstall pyoos-${version}.tar.gz && popd

script:
  - if [[ $TRAVIS_JOB_NAME == 'default' ]] || [[ $TRAVIS_JOB_NAME == 'legacy_python' ]]; then
      cp -r tests /tmp && cd /tmp ;
      pytest -n 2 -rxs -vv tests ;
    fi

  - if [[ $TRAVIS_JOB_NAME == 'coding_standards' ]]; then
      pytest --flake8 -m flake8 ;
    fi

notifications:
  flowdock: 2dd835dfbdbc64986ba043fffa654836,1d5af475ae38ec1d874c752c23558d2d
